### ISSUE TITLE
Highlighting the specific word in a sentence

### ISSUE THREAD

**Issue by manojleaton** [etn-ccis/blui-react-workflows#313]
#### Describe the bug / expected behavior
If we want to highlight any word in a sentence, need to add customisation to the word and pass it along with the sentence to  `Trans` component

#### What are the steps to reproduce?

1. Go to ForgotPasswordScreen component file in the project directory and check it

#### Screenshots / Screen recording

<img width="709" alt="Screenshot 2023-06-22 at 3 18 53 PM" src="https://github.com/etn-ccis/blui-react-workflows/assets/130662346/63539501-416a-47ca-99fd-988043f66730">

**Comment by manojleaton** [comment]
@huayunh In the screenshot below, as you can see "one business day" and "1-800-123-4567" strings are styled differently than other texts in the description. So in combine of these two styles I added as highlight. 

<img width="1440" alt="Screenshot 2023-06-09 at 4 21 39 PM" src="https://github.com/etn-ccis/blui-react-workflows/assets/130662346/37abac92-8006-4bd1-b4c1-fdd1d81e84b2">

**Comment by joebochill** [comment]
Hey @manojleaton — I'm not sure exactly what you are reporting as the bug in this issue. The full ForgotPassword screen component looks correct in the example2 project (as per your screen shot above) and the Trans component is being used correctly? 

Customization in the end-user/example application also works as expected (I had to fix a small bug in the component to call the function prop instead of trying to render a function):
<img width="554" alt="image" src="https://github.com/etn-ccis/blui-react-workflows/assets/29152776/0f271f3c-c708-4d05-a19d-bf59fbebd422">


If this is still an issue can you please elaborate on what you are trying to do and what the expected behavior is?
